import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { PlanNameForm } from "./plan-name-form";
import { createV2Plan, renameV2Plan } from "./actions";
import type { PlanNameResult } from "./types";
const router = vi.hoisted(() => ({ replace: vi.fn(), refresh: vi.fn() }));
vi.mock("next/navigation", () => ({ useRouter: () => router, unstable_rethrow: vi.fn() }));
vi.mock("./actions", () => ({ createV2Plan: vi.fn(), renameV2Plan: vi.fn() }));
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
beforeEach(() => vi.resetAllMocks());
it("creates once while pending, submits the name, and opens the persisted plan", async () => {
  let finish!: (result: PlanNameResult) => void;
  vi.mocked(createV2Plan).mockReturnValue(new Promise(resolve => { finish = resolve; }));
  render(<PlanNameForm />);
  fireEvent.change(screen.getByLabelText("Plan name"), { target: { value: " Upper " } });
  const form = screen.getByRole("form");
  act(() => { fireEvent.submit(form); fireEvent.submit(form); });
  expect(createV2Plan).toHaveBeenCalledOnce();
  expect(vi.mocked(createV2Plan).mock.calls[0][0].get("name")).toBe(" Upper ");
  expect(screen.getByRole("button", { name: "Creating…" })).toBeDisabled();
  expect(router.replace).not.toHaveBeenCalled();
  await act(async () => finish({ status: "success", plan: { id: "created", name: "Upper" } }));
  expect(router.replace).toHaveBeenCalledWith("/v2/library/plans/created");
  expect(router.refresh).toHaveBeenCalledOnce();
  expect(screen.getByRole("button", { name: "Creating…" })).toBeDisabled();
});
it("retains a failed create draft so it can be corrected and retried", async () => {
  vi.mocked(createV2Plan).mockResolvedValueOnce({ status: "error", message: "A plan already exists." }).mockResolvedValueOnce({ status: "success", plan: { id: "new", name: "Lower" } });
  render(<PlanNameForm />);
  fireEvent.change(screen.getByLabelText("Plan name"), { target: { value: "Upper" } });
  fireEvent.submit(screen.getByRole("form"));
  expect(await screen.findByRole("alert")).toHaveTextContent("A plan already exists.");
  expect(screen.getByLabelText("Plan name")).toHaveValue("Upper");
  expect(router.replace).not.toHaveBeenCalled();
  fireEvent.change(screen.getByLabelText("Plan name"), { target: { value: "Lower" } });
  fireEvent.submit(screen.getByRole("form"));
  await waitFor(() => expect(router.replace).toHaveBeenCalledWith("/v2/library/plans/new"));
});
it("renames in place using the returned normalized name and supports discarding the next edit", async () => {
  vi.mocked(renameV2Plan).mockResolvedValue({ status: "success", plan: { id: "plan", name: "Upper strength" } });
  render(<PlanNameForm plan={{ id: "plan", name: "Upper" }} />);
  expect(screen.getByRole("button", { name: "Save name" })).toBeDisabled();
  fireEvent.change(screen.getByLabelText("Plan name"), { target: { value: " Upper   strength " } });
  fireEvent.submit(screen.getByRole("form"));
  expect(await screen.findByRole("status")).toHaveTextContent("Plan name saved.");
  expect(vi.mocked(renameV2Plan).mock.calls[0][0].get("templateId")).toBe("plan");
  expect(screen.getByLabelText("Plan name")).toHaveValue("Upper strength");
  expect(router.replace).not.toHaveBeenCalled();
  expect(router.refresh).toHaveBeenCalledOnce();
  fireEvent.change(screen.getByLabelText("Plan name"), { target: { value: "Mistake" } });
  fireEvent.click(screen.getByRole("button", { name: "Discard changes" }));
  expect(screen.getByLabelText("Plan name")).toHaveValue("Upper strength");
  expect(screen.queryByRole("status")).not.toBeInTheDocument();
});
it("keeps rename drafts and offers retry after a transport failure", async () => {
  vi.mocked(renameV2Plan).mockRejectedValue(new Error("network"));
  render(<PlanNameForm plan={{ id: "plan", name: "Upper" }} />);
  fireEvent.change(screen.getByLabelText("Plan name"), { target: { value: "Lower" } });
  fireEvent.submit(screen.getByRole("form"));
  expect(await screen.findByRole("alert")).toHaveTextContent("Check your library");
  expect(screen.getByLabelText("Plan name")).toHaveValue("Lower");
  expect(screen.getByRole("button", { name: "Save name" })).toBeEnabled();
  expect(router.refresh).not.toHaveBeenCalled();
});
it("warns on app links and unload only while a name is unsaved", () => {
  const confirm = vi.spyOn(window, "confirm").mockReturnValue(false);
  render(<><PlanNameForm plan={{ id: "plan", name: "Upper" }} /><a href="/v2/library">Library</a></>);
  fireEvent.change(screen.getByLabelText("Plan name"), { target: { value: "Lower" } });
  fireEvent.click(screen.getByRole("link", { name: "Library" }));
  expect(confirm).toHaveBeenCalledWith("Leave this plan? Your unsaved name will be lost.");
  const event = new Event("beforeunload", { cancelable: true });
  window.dispatchEvent(event);
  expect(event.defaultPrevented).toBe(true);
  fireEvent.click(screen.getByRole("button", { name: "Discard changes" }));
  const cleanEvent = new Event("beforeunload", { cancelable: true });
  window.dispatchEvent(cleanEvent);
  expect(cleanEvent.defaultPrevented).toBe(false);
});
